# -*- coding: utf-8 -*-
# 论文主参考文献数据（顺序编码制，GB/T 7714—2015）。
# [1]-[49] 为第1-2章已联网核实文献；[50]-[56] 为第3、4章新增、已核实文献；
# [57]-[61] 为与本文最接近的LLM/KG工作，已联网核实（GB/T 7714）。
REF = {
1: '上海市人民政府. 上海市防汛防台专项应急预案[EB/OL]. (2025)[2026-09-23]. https://cdn.shanghai.gov.cn/.',
2: '上海市浦东新区防汛指挥部. 浦东新区防汛防台专项应急预案(修订)[EB/OL]. (2025)[2026-09-23]. https://www.pudong.gov.cn/.',
3: '上海市水务局. 上海交通行业防汛防台专项应急预案[EB/OL]. (2022)[2026-09-23]. https://swj.sh.gov.cn/.',
4: '上海市水务局. 上海市城镇雨水排水规划(2020—2035)[EB/OL]. (2021)[2026-09-23]. https://swj.sh.gov.cn/.',
5: '交通运输部. 城市轨道交通运营防汛防台风指南[EB/OL]. (2026)[2026-09-23].',
6: '北京市人民政府. 北京市交通行业防汛应急预案[EB/OL]. (2019)[2026-09-23]. https://www.beijing.gov.cn/.',
7: '北京市交通委员会. 地铁站外积水达30厘米关闭站口[EB/OL]. (2026)[2026-09-23].',
8: '合肥市交通运输局. 极端天气预警合肥市轨道交通运营应对方案[EB/OL]. (2023)[2026-09-23].',
9: '杭州市轨道交通. 台风期间杭州地铁运营调整[EB/OL]. (2026)[2026-09-23].',
10: '南京市溧水区人民政府. 南京市溧水区特大暴雨城市防洪避险预案[EB/OL]. (2024)[2026-09-23].',
11: '绍兴京越地铁. 绍兴京越地铁防汛专项应急预案[EB/OL]. (2025)[2026-09-23].',
12: '中华人民共和国住房和城乡建设部. 地铁设计规范: GB 50157—2013[S]. 北京: 中国建筑工业出版社, 2013.',
13: '国家标准化管理委员会. 地铁安全疏散规范: GB/T 33668—2017[S]. 北京: 中国标准出版社, 2017.',
14: '中国勘察设计协会. 城市轨道交通车站行人仿真评估标准: T/CECAS 20010—2026[S]. 2026.',
15: '深圳市市场监督管理局. 地下空间防汛建设与管理规程: DB4403/T 552—2024[S]. 2024.',
16: '中国工程建设标准化协会. 内涝风险评估标准(征求意见稿)[S]. 2024.',
17: '国务院灾害调查组. 河南郑州“7·20”特大暴雨灾害调查报告[R/OL]. (2022)[2026-09-23]. https://www.mem.gov.cn/.',
18: '应急管理部. 国务院调查组就郑州“7·20”调查情况答记者问[EB/OL]. (2022)[2026-09-23]. https://www.mem.gov.cn/.',
19: '胡明伟, 汤静妍, 何国庆. 地铁车站水侵应急疏散仿真研究[J]. 深圳大学学报(理工版), 2022, 39(2): 159-167.',
20: '吕海敏, 陈小冰, 陈湘生, 徐涛, 张嘉轩. 极端暴雨导致城市地铁水灾: 现状、成因及防洪措施[J]. 深圳大学学报(理工版), 2026, 43(3).',
21: '陈柯吟, 郑哲, 林佳瑞, 周育丞. 基于BIM的洪灾场景地铁疏散快速模拟[C]//第八届全国BIM学术会议论文集. 2022.',
22: '朱文浩, 朱海燕, 刘志钢, 沈雨欣, 邵昀泓, 洪敏. 水灾场景下积水深度对地铁应急疏散的影响研究[J]. 城市轨道交通研究, 2025, 28(8): 243-247,253.',
23: 'PARK S, LEE G, KIM J O. Flood evacuation mapping using a time-distance cartogram[J]. ISPRS International Journal of Geo-Information, 2020, 9(4): 207.',
24: 'LI X, GUO C, CHEN J, QIN Y, ZHANG J, BODE N W F, SONG W. Pedestrian dynamics in flooding disasters: an experimental study of unidirectional pedestrian flow under multiple water depths[J]. Journal of Hydrology, 2026, 672: 135395.',
25: 'SHIRVANI M, KESSERWANI G. Flood-pedestrian simulator for modelling human response dynamics during flood-induced evacuation: Hillsborough stadium case study[J]. Natural Hazards and Earth System Sciences, 2021, 21: 3175.',
26: '李航, 陈鹏. 城市暴雨内涝灾害期间居民步行安全阈值研究[J]. 水利水电快报, 2021, 42(7): 6-10.',
27: 'PARK D, PARK I, YOO M, RHEE D S. Impact of flood progression on evacuation in underground metro[J]. Applied Sciences, 2026, 16(18): 8952. DOI: 10.3390/app16188952.',
28: 'ZHU Z F, ZHANG Y P, GOU L F, PANG B. An entropic approach to estimating the instability criterion of people in floodwaters[J]. Entropy, 2021, 23(1): 74.',
29: '王慧亮, 严登明, 刘宏伟, 吴泽宁, 周易宏. 城市洪涝个性化应急避险路径动态规划方法与应用[J]. 水科学进展, 2026, 37(3): 465-479.',
30: 'PARK J S, O\u2019BRIEN J C, CAI C J, et al. Generative Agents: Interactive Simulacra of Human Behavior[C]//UIST. 2023.',
31: 'XI Z, ZHANG W, ZHU Y, et al. The Rise and Potential of Large Language Model Based Agents: A Survey[EB/OL]. arXiv:2309.07864, 2023.',
32: 'ROGERS R W. A protection motivation theory of fear appeals and attitude change[J]. Journal of Psychology, 1975, 91(1): 93-114.',
33: 'AJZEN I. The theory of planned behavior[J]. Organizational Behavior and Human Decision Processes, 1991, 50(2): 179-211.',
34: 'KAHNEMAN D, TVERSKY A. Prospect theory: An analysis of decision under risk[J]. Econometrica, 1979, 47(2): 263-291.',
35: 'SIMON H A. A behavioral model of rational choice[J]. Quarterly Journal of Economics, 1955, 69(1): 99-118.',
36: 'HELBING D, MOLNÁR P. Social force model for pedestrian dynamics[J]. Physical Review E, 1995, 51(5): 4282-4286.',
37: 'HELBING D, FARKAS I, VICSEK T. Simulating dynamical features of escape panic[J]. Nature, 2000, 407: 487-490.',
38: 'BANDURA A. Social Learning Theory[M]. Englewood Cliffs: Prentice-Hall, 1977.',
39: 'LATANÉ B. The psychology of social impact[J]. American Psychologist, 1981, 36(4): 343-356.',
40: 'NONAKA I. A dynamic theory of organizational knowledge creation[J]. Organization Science, 1994, 5(1): 14-37.',
41: '王飞跃. 平行系统方法与复杂系统的管理和控制[J]. 控制与决策, 2004, 19(5): 485-489.',
42: 'REASON J. Human Error[M]. Cambridge: Cambridge University Press, 1990.',
43: 'BERTALANFFY L VON. General System Theory[M]. New York: George Braziller, 1968.',
44: 'LEWIS P, PEREZ E, PIKTUS A, et al. Retrieval-Augmented Generation for Knowledge-Intensive NLP Tasks[C]//NeurIPS. 2020.',
45: 'BROWN T B, MANN B, RYDER B, et al. Language Models are Few-Shot Learners[C]//NeurIPS. 2020.',
46: 'WEI J, WANG X, SCHUURMANS D, et al. Chain-of-Thought Prompting Elicits Reasoning in Large Language Models[C]//NeurIPS. 2022.',
47: 'BUBECK S, CHANDRASEKARAN V, ELDAN R, et al. Sparks of Artificial General Intelligence: Early experiments with GPT-4[EB/OL]. arXiv:2303.12712, 2023.',
48: 'ARGYLE L P, BUSBY E C, FULDA N, et al. Out of One, Many: Using Language Models to Simulate Human Society[J]. Political Analysis, 2023.',
49: 'HORTON J J. Large Language Models as Simulated Economic Agents: What Can We Learn from Homo Silicus?[EB/OL]. arXiv:2301.07864, 2023.',
50: 'GRUBER T R. A translation approach to portable ontology specifications[J]. Knowledge Acquisition, 1993, 5(2): 199-220.',
51: 'NOY N F, McGUINNESS D L. Ontology Development 101: A Guide to Creating Your First Ontology[R]. Stanford: Stanford Knowledge Systems Laboratory, KSL-01-05, 2001.',
52: 'FRUIN J J. Pedestrian Planning and Design[M]. New York: Metropolitan Association of Urban Designers and Environmental Planners, 1971.',
53: 'KAZIL J, MASAD D, CROOKS A. Utilizing Python for agent-based modeling: the Mesa framework[C]//Social, Cultural, and Behavioral Modeling. Cham: Springer, 2020: 308-317.',
54: 'HURLEY M J, GOTTUK D, HALL J R, et al, eds. SFPE Handbook of Fire Protection Engineering[M]. 5th ed. New York: Springer, 2016.',
55: '中华人民共和国住房和城乡建设部. 城镇内涝防治技术规范: GB 51222—2017[S]. 北京: 中国计划出版社, 2017.',
56: 'TVERSKY A, KAHNEMAN D. Judgment under uncertainty: heuristics and biases[J]. Science, 1974, 185(4157): 1124-1131.',
57: '王喆, 陆俊燃, 杨栋梁, 李墨潇. 融合GPT和知识图谱的洪涝应急决策智能问答系统研究[J]. 中国安全生产科学技术, 2024, 20(4): 5-11.',
58: 'ZHU J, DANG P, CAO Y, LAI J, GUO Y, WANG P, LI W. A flood knowledge-constrained large language model interactable with GIS: enhancing public risk perception of floods[J]. International Journal of Geographical Information Science, 2024, 38(4): 603-625.',
59: 'YANG X X, WAN J H, LI Y X, et al. A knowledge-data dual-driven framework for intelligent flood evacuation in subway stations[J]. Physica A: Statistical Mechanics and its Applications, 2025, 678: 130924.',
60: '李维炼, 冉青青, 党沛, 朱军, 朱庆, 张恒. 耦合LLMs-KG的地下车站设施洪水脆弱性级联效应分析方法[J]. 测绘学报, 2026, 55(1): 154-168.',
61: 'CHEN R, WANG C, SUN Y, ZHAO X, XU S. From perceptions to decisions: wildfire evacuation decision prediction with behavioral theory-informed LLMs[C]//Proceedings of the 63rd Annual Meeting of the Association for Computational Linguistics (Long Papers). Vienna: ACL, 2025: 29754-29778.',
# [62]-[85] 为扩充文献综述而补充的疏散行为、行人建模与涉水安全经典文献，均已联网核实；
62: 'LINDELL M K, PERRY R W. The protective action decision model: theoretical modifications and additional evidence[J]. Risk Analysis, 2012, 32(4): 616-632.',
63: 'PERRY R W, LINDELL M K. Preparedness for emergency response: guidelines for the emergency planning process[J]. Disasters, 2003, 27(4): 336-350.',
64: 'DASH N, GLADWIN H. Evacuation decision making and behavioral responses: individual and household[J]. Natural Hazards Review, 2007, 8(3): 69-77.',
65: 'SORENSEN J H. Hazard warning systems: review of 20 years of progress[J]. Natural Hazards Review, 2000, 1(2): 119-125.',
66: 'WACHINGER G, RENN O, BEGG C, KUHLICKE C. The risk perception paradox—implications for governance and communication of natural hazards[J]. Risk Analysis, 2013, 33(6): 1049-1065.',
67: 'MAWSON A R. Understanding mass panic and other collective responses to threat and disaster[J]. Psychiatry, 2005, 68(2): 95-113.',
68: 'KULIGOWSKI E D. Predicting human behavior during fires[J]. Fire Technology, 2013, 49(1): 101-120.',
69: 'DRURY J, COCKING C, REICHER S. Everyone for themselves? A comparative study of crowd solidarity among emergency survivors[J]. British Journal of Social Psychology, 2009, 48(3): 487-506.',
70: 'TERPSTRA T. Emotions, trust, and perceived risk: affective and cognitive routes to flood preparedness behavior[J]. Risk Analysis, 2011, 31(10): 1658-1675.',
71: 'BUBECK P, BOTZEN W J W, AERTS J C J H. A review of risk perceptions and other factors that influence flood mitigation behavior[J]. Risk Analysis, 2012, 32(9): 1481-1495.',
72: 'BURSTEDDE C, KLAUCK K, SCHADSCHNEIDER A, ZITTARTZ J. Simulation of pedestrian dynamics using a two-dimensional cellular automaton[J]. Physica A: Statistical Mechanics and its Applications, 2001, 295(3-4): 507-525.',
73: 'KIRCHNER A, SCHADSCHNEIDER A. Simulation of evacuation processes using a bionics-inspired cellular automaton model for pedestrian dynamics[J]. Physica A: Statistical Mechanics and its Applications, 2002, 312(1-2): 260-276.',
74: 'DUIVES D C, DAAMEN W, HOOGENDOORN S P. State-of-the-art crowd motion simulation models[J]. Transportation Research Part C: Emerging Technologies, 2013, 37: 193-210.',
75: 'ZHENG X P, ZHONG T K, LIU M T. Modeling crowd evacuation of a building based on seven methodological approaches[J]. Building and Environment, 2009, 44(3): 437-445.',
76: 'GWYNNE S, GALEA E R, OWEN M, LAWRENCE P J, FILIPPIDIS L. A review of the methodologies used in evacuation modelling[J]. Fire and Materials, 1999, 23(6): 383-388.',
77: 'ISHIGAKI T, BABA Y, TODA K, INOUE K. Experimental study on evacuation from underground space in urban flood[C]//Proceedings of the 31st IAHR Congress. 2005: 1116-1123.',
78: 'JONKMAN S N, PENNING-ROWSELL E. Human instability in flood flows[J]. Journal of the American Water Resources Association, 2008, 44(5): 1208-1218.',
79: 'XIA J Q, FALCONER R A, WANG Y J, XIAO X W. New criterion for the stability of a human body in floodwaters[J]. Journal of Hydraulic Research, 2014, 52(1): 93-104.',
80: 'JONKMAN S N, VRIJLING J K, VROUWENVELDER A. Methods for the estimation of loss of life due to floods: a literature review and a proposal for a new method[J]. Natural Hazards, 2008, 46(3): 353-389.',
81: 'JONKMAN S N, KELMAN I. An analysis of the causes and circumstances of flood disaster deaths[J]. Disasters, 2005, 29(1): 75-97.',
82: 'MILANESI L, PILOTTI M, BACCHI B. Using web-based observations to identify thresholds of a person’s stability in a flow[J]. Water Resources Research, 2016, 52(10): 7793-7805.',
83: 'TANG Y, ZHOU T Z, ZHONG Y X, et al. Risk assessment for critical flood height of pedestrian escape in subway station[J]. Water, 2022, 14(21): 3409.',
84: 'TSUKAHARA M, KOSHIBA Y, OHTANI H. Effectiveness of downward evacuation in a large-scale subway fire using Fire Dynamics Simulator[J]. Tunnelling and Underground Space Technology, 2011, 26(4): 573-581.',
85: 'LEI W S, LI A G, GAO R, HAO X P, DENG B S. Simulation of pedestrian crowds’ evacuation in a huge transit terminal subway station[J]. Physica A: Statistical Mechanics and its Applications, 2012, 391(22): 5355-5365.',
# [86]-[101] 为LLM智能体、知识图谱、机器学习与数字孪生方法学经典文献，均已联网核实；
86: 'WANG L, MA C, FENG X Y, et al. A survey on large language model based autonomous agents[J]. Frontiers of Computer Science, 2024, 18(6): 186345.',
87: 'SUMERS T R, YAO S Y, NARASIMHAN K, GRIFFITHS T L. Cognitive architectures for language agents[J]. Transactions on Machine Learning Research, 2024.',
88: 'AHER G V, ARRIAGA R I, KALAI A T. Using large language models to simulate multiple humans and replicate human subject studies[C]//Proceedings of the 40th International Conference on Machine Learning. PMLR, 2023, 202: 337-371.',
89: 'YAO S Y, ZHAO J, YU D, et al. ReAct: synergizing reasoning and acting in language models[C]//International Conference on Learning Representations. 2023.',
90: 'SHINN N, CASSANO F, GOPINATH A, NARASIMHAN K, YAO S Y. Reflexion: language agents with verbal reinforcement learning[C]//Advances in Neural Information Processing Systems. 2023, 36.',
91: 'WU Q Y, BANSAL G, ZHANG J Y, et al. AutoGen: enabling next-gen LLM applications via multi-agent conversation[C]//Conference on Language Modeling. 2024.',
92: 'HOGAN A, BLOMQVIST E, COCHEZ M, et al. Knowledge graphs[J]. ACM Computing Surveys, 2021, 54(4): 1-37.',
93: 'STUDER R, BENJAMINS V R, FENSEL D. Knowledge engineering: principles and methods[J]. Data & Knowledge Engineering, 1998, 25(1-2): 161-197.',
94: 'BERNERS-LEE T, HENDLER J, LASSILA O. The semantic web[J]. Scientific American, 2001, 284(5): 34-43.',
95: 'CHEN T Q, GUESTRIN C. XGBoost: a scalable tree boosting system[C]//Proceedings of the 22nd ACM SIGKDD International Conference on Knowledge Discovery and Data Mining. 2016: 785-794.',
96: 'LUNDBERG S M, LEE S I. A unified approach to interpreting model predictions[C]//Advances in Neural Information Processing Systems. 2017, 30: 4765-4774.',
97: 'HAN J W, PEI J, YIN Y W. Mining frequent patterns without candidate generation[C]//Proceedings of the 2000 ACM SIGMOD International Conference on Management of Data. 2000: 1-12.',
98: 'AGRAWAL R, SRIKANT R. Fast algorithms for mining association rules[C]//Proceedings of the 20th International Conference on Very Large Data Bases. 1994: 487-499.',
99: 'BREIMAN L. Random forests[J]. Machine Learning, 2001, 45(1): 5-32.',
100: 'KE G, MENG Q, FINLEY T, et al. LightGBM: a highly efficient gradient boosting decision tree[C]//Advances in Neural Information Processing Systems. 2017, 30: 3149-3157.',
101: 'TAO F, ZHANG H, LIU A, NEE A Y C. Digital twin in industry: state-of-the-art[J]. IEEE Transactions on Industrial Informatics, 2019, 15(4): 2405-2415.',
}

# 中文期刊文献的官方英文对照（期刊要求中文期刊[J]需中英文列出）；键为 REF 序号
REF_EN = {
19: 'HU Mingwei, TANG Jingyan, HE Guoqing. Simulation study on emergency evacuation due to water invasion in subway stations[J]. Journal of Shenzhen University Science and Engineering, 2022, 39(2): 159-167.',
22: 'ZHU Wenhao, ZHU Haiyan, LIU Zhigang, SHEN Yuxin, SHAO Yunhong, HONG Min. Impact of water depth on subway emergency evacuation in flood scenarios[J]. Urban Mass Transit, 2025, 28(8): 243-247,253.',
26: 'LI Hang, CHEN Peng. Study on pedestrian travel safety threshold during urban rainstorm and waterlogging disaster[J]. Express Water Resources & Hydropower Information, 2021, 42(7): 6-10.',
41: 'WANG Fei-Yue. Parallel system methods for management and control of complex systems[J]. Control and Decision, 2004, 19(5): 485-489.',
57: 'WANG Zhe, LU Junran, YANG Dongliang, LI Moxiao. Research on intelligent question-answering system for flood emergency decision-making with fusion of GPT and knowledge graph[J]. Journal of Safety Science and Technology, 2024, 20(4): 5-11.',
60: 'LI Weilian, RAN Qingqing, DANG Pei, ZHU Jun, ZHU Qing, ZHANG Heng. A coupled LLMs-KG method for cascading flood vulnerability analysis of underground station facilities[J]. Acta Geodaetica et Cartographica Sinica, 2026, 55(1): 154-168.',
}
